# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Symbolic-Custom-CCompiler
version:      1.02
version_from: lib/Math/Symbolic/Custom/CCompiler.pm
installdirs:  site
requires:
    Inline::C:                     0.44
    Math::Symbolic:                0.509
    Test::More:                    0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
